#!/bin/sh
input=$1
target=""
ip=""
while [ -z $target ]; do
	case $input in
		s|S|server|bin/server|./bin/client)
			target="bin/server";;
		c|C|client|bin/client|./bin/client)
			target="bin/client"
			ip="127.0.0.1";;
		*) read -p "[client/server]: " input;;
	esac
done

# build
make $target

# start
./$target $ip 5555
