#!/bin/sh

input=$1
BINDIR='bin'
CLIENT='client'
SERVER='server'

while [ -z $target ]; do
  case $input in
    [Ss]*) target=$SERVER;;
    [Cc]*)
      target=$CLIENT
      ip='127.0.0.1';;
    *) read -p "[$CLIENT/$SERVER]: " input;;
  esac
done

if [ ! -x $BINDIR/$target ]; then
  mkdir -p $BINDIR
  make $BINDIR/$target
fi

$BINDIR/$target $ip 5555
