#!/bin/sh
input=$1
bin="bin"
client="client"
server="server"

while [ -z $target ]; do
	case $input in
		s|S|server|bin/server|./bin/client)
			target=$server;;
		c|C|client|bin/client|./bin/client)
			target=$client
			ip="127.0.0.1";;
		*) read -p "[$client/$server]: " input;;
	esac
done

# build
[ -d $bin ] || mkdir $bin
make $bin/$target

# start
./$bin/$target $ip 5555
